/*
  # Visionario Boosting - Initial Schema

  ## Tables

  1. **accounts** - Discord bot tokens stored for boosting
     - id, token (encrypted display), token_hash, token_full, nitro_slots, is_valid, username, avatar, created_at

  2. **boost_keys** - Keys generated by admin to hand to users
     - id, key_value (60-char unique), boost_count, max_boosts, used, used_at, guild_id, guild_name, created_at

  3. **boost_tasks** - Tracks ongoing/completed boost jobs
     - id, key_id, guild_id, guild_name, guild_icon, status, stats (jsonb), tokens_detail (jsonb), created_at, updated_at

  ## Security
  - RLS enabled on all tables
  - Only service_role can access (all operations go through edge functions)
*/

CREATE TABLE IF NOT EXISTS accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token_full text NOT NULL,
  token_short text GENERATED ALWAYS AS (left(token_full, 28)) STORED,
  username text DEFAULT '',
  discriminator text DEFAULT '',
  avatar_url text DEFAULT '',
  nitro_slots int DEFAULT 0,
  is_valid boolean DEFAULT true,
  has_nitro boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only - accounts select"
  ON accounts FOR SELECT
  TO service_role
  USING (true);

CREATE POLICY "Service role only - accounts insert"
  ON accounts FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role only - accounts update"
  ON accounts FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role only - accounts delete"
  ON accounts FOR DELETE
  TO service_role
  USING (true);

CREATE TABLE IF NOT EXISTS boost_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key_value text UNIQUE NOT NULL,
  label text DEFAULT '',
  boost_count int NOT NULL DEFAULT 1,
  is_used boolean DEFAULT false,
  used_at timestamptz,
  guild_id text DEFAULT '',
  guild_name text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE boost_keys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only - keys select"
  ON boost_keys FOR SELECT
  TO service_role
  USING (true);

CREATE POLICY "Service role only - keys insert"
  ON boost_keys FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role only - keys update"
  ON boost_keys FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role only - keys delete"
  ON boost_keys FOR DELETE
  TO service_role
  USING (true);

CREATE TABLE IF NOT EXISTS boost_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key_id uuid REFERENCES boost_keys(id),
  guild_id text DEFAULT '',
  guild_name text DEFAULT '',
  guild_icon text DEFAULT '',
  invite_code text DEFAULT '',
  status text DEFAULT 'pending',
  stats jsonb DEFAULT '{"total":0,"joined":0,"boosted":0,"failed":0,"total_boosts":0}'::jsonb,
  tokens_detail jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE boost_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only - tasks select"
  ON boost_tasks FOR SELECT
  TO service_role
  USING (true);

CREATE POLICY "Service role only - tasks insert"
  ON boost_tasks FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role only - tasks update"
  ON boost_tasks FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_token text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz DEFAULT (now() + interval '12 hours')
);

ALTER TABLE admin_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only - sessions select"
  ON admin_sessions FOR SELECT
  TO service_role
  USING (true);

CREATE POLICY "Service role only - sessions insert"
  ON admin_sessions FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role only - sessions delete"
  ON admin_sessions FOR DELETE
  TO service_role
  USING (true);
